### ISSUE TITLE
LocalTpmSetLocality

### ISSUE THREAD

**Issue by leeehui** [intel/tpm2-tss#696]
Hi, 
I just found that "LocalTpmSetLocality" is not supported in "tcti_device.c" because :
 /*
     * Linux driver doesn't expose a mechanism for user space applications
     * to set locality.
     */
so, my question is why TCTI has defined the interface as it is not supported by linux driver?
will it be supported in the future?
according to my knowledge of TPM, Locality control is special feature of which the implementation is platform specific, so this interface is reserved for user implementing the locality control interface according to specific platform, is this reasonable?
thanks!

**Comment by flihp** [comment]
Working through your questions in order:
1) The TCTI spec requires that we implement a function for setting the locality even if the underlying mechanism (the linux kernel driver in this case) doesn't support it. So this function just returns a response code to let the caller know that the feature isn't implemented. We do this so that software gets a consistent interface and behavior from all TCTIs.
2) Whether or not the Linux TPM drive will ever expose a mechanism for setting locality is beyond my knowledge. All TPM device driver development is discussed on the linux-integrity mailing list these days: http://vger.kernel.org/vger-lists.html#linux-integrity.
3) Your understanding of the locality control interface sounds accurate to me.
