### ISSUE TITLE
make fails: No rule to make target man/man3/InitSocketTcti.3

### ISSUE THREAD

**Issue by pscheie** [intel/tpm2-tss#728]
I've downloaded the source tar file (I'm on a system with no internet access so can't use git) and I'm trying to build it on CentOS 7.  ./configure runs okay, but when I run 'make', it fails on what appears to be a man page:

"make: *** No rule to make target 'man/man3/InitSocketTcti.3',  needed by 'all-am'. Stop"

The file man/man3/InitSocketTcti.3 is there and appears to be a properly formatted man page.

Any suggestions as to what's causing this failure?  Thanks.

**Comment by flihp** [comment]
That's weird for sure. What version of centos and relevant packages? We've had problems with centos in the past since they stopped packaging the autoconf-archive so this could be related.

**Comment by pscheie** [comment]
CentOS 7.  I'm not sure how to answer "relevant packages"; I've got everything mentioned in the INSTALL file as a requirement.  I am confused about the CONFIG_SITE variable; INSTALL says there is a default_config.site in lib/ but I don't see it.

FWIW, on another CentOS 7 machine that does have internet access, I went the git clone route and that worked, that is I was able to build it successfully, but that was using the bootstrap script (skipping the dnf step for Fedora because CentOS doesn't have that).  

I suspect for the man page problem I'm missing a package or environment variable or something.

**Comment by flihp** [comment]
Sorry but the junk about the CONFIG_SITE file should have been removed. I'll get an issue for that cleanup into the queue (https://github.com/intel/tpm2-abrmd/issues/305) . I learned the hard way that I was abusing the CONFIG_SITE mechanism. Either way it's good to know you've made it past this hickup. Closing this since you've managed to get a build done on a different system but feel free to open it back up if you need to.
